#database.yml
development:
  adapter: postgresql
  database: accessibility-reports
  username: postgres
  encoding: utf8
  password: tiger
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: accessibility-reports
  username: postgres
  encoding: utf8
  password: tiger
  host: localhost
  pool: 5
