Website.create!([
  {website_url: "http://gradresearch.unimelb.edu.au", website_name: "Graduate Research"},
  {website_url: "http://www.unimelb.edu.au/", website_name: "Varied-Sample"}
])
Report.create!([
  {report_date: "2014-11-25 00:00:00", website_id: 1, pages_total: 10, pages_error: 6, total_errors: 10, total_alerts: 253},
  {report_date: "2014-11-25 00:00:00", website_id: 2, pages_total: 10, pages_error: 8, total_errors: 34, total_alerts: 503}
])
Page.create!([
  {report_id: 1, page_url: "http://gradresearch.unimelb.edu.au", page_title: "The Melbourne School Of Graduate Research - Home", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au"},
  {report_id: 1, page_url: "http://gradresearch.unimelb.edu.au/staff/index.html", page_title: "The Melbourne School Of Graduate Research - For Staff", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/staff/index.html"},
  {report_id: 1, page_url: "http://gradresearch.unimelb.edu.au/3MT/index.html", page_title: "The Melbourne School Of Graduate Research -", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/3MT/index.html"},
  {report_id: 1, page_url: "http://gradresearch.unimelb.edu.au/programs/upskills/index.html", page_title: "The Melbourne School Of Graduate Research - UpSkills", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/programs/upskills/index.html"},
  {report_id: 1, page_url: "http://gradresearch.unimelb.edu.au/news/index.html", page_title: "The Melbourne School Of Graduate Research - News", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/news/index.html"},
  {report_id: 1, page_url: "http://gradresearch.unimelb.edu.au/handbooks/index.html", page_title: "The Melbourne School Of Graduate Research - Handbooks", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/handbooks/index.html"},
  {report_id: 1, page_url: "http://gradresearch.unimelb.edu.au/messenger/index.html", page_title: "The Melbourne School Of Graduate Research - Messenger", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/messenger/index.html"},
  {report_id: 1, page_url: "http://gradresearch.unimelb.edu.au/programs/index.html", page_title: "The Melbourne School Of Graduate Research - Research Training & Professional Development", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/programs/index.html"},
  {report_id: 1, page_url: "http://gradresearch.unimelb.edu.au/msgr/", page_title: "The Melbourne School Of Graduate Research - About the Melbourne School of Graduate Research", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/msgr/"},
  {report_id: 1, page_url: "http://gradresearch.unimelb.edu.au/news/MSGR.html", page_title: "The Melbourne School Of Graduate Research - News", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/news/MSGR.html"},
  {report_id: 2, page_url: "http://about.unimelb.edu.au/academicboard", page_title: "Home : Academic Board", wave_url: "http://wave.webaim.org/report?url=http://about.unimelb.edu.au/academicboard"},
  {report_id: 2, page_url: "http://arts.unimelb.edu.au/", page_title: "Faculty of Arts | Faculty of Arts", wave_url: "http://wave.webaim.org/report?url=http://arts.unimelb.edu.au/"},
  {report_id: 2, page_url: "http://ask.unimelb.edu.au/", page_title: "ask.unimelb : Ask Unimelb", wave_url: "http://wave.webaim.org/report?url=http://ask.unimelb.edu.au/"},
  {report_id: 2, page_url: "http://blog.le.unimelb.edu.au/", page_title: "Learning Environments blog", wave_url: "http://wave.webaim.org/report?url=http://blog.le.unimelb.edu.au/"},
  {report_id: 2, page_url: "http://blogs.unimelb.edu.au/ask-counselling/", page_title: "Ask Counselling | Counselling and Psychological Services", wave_url: "http://wave.webaim.org/report?url=http://blogs.unimelb.edu.au/ask-counselling/"},
  {report_id: 2, page_url: "http://blogs.unimelb.edu.au/staffnews/", page_title: "Staff News \u00BB Just another blogs.unimelb weblog", wave_url: "http://wave.webaim.org/report?url=http://blogs.unimelb.edu.au/staffnews/"},
  {report_id: 2, page_url: "http://careers.unimelb.edu.au/home", page_title: "Home : Careers and Employment", wave_url: "http://wave.webaim.org/report?url=http://careers.unimelb.edu.au/home"},
  {report_id: 2, page_url: "http://cat.lib.unimelb.edu.au/", page_title: "Catalogue : Library : The University of Melbourne", wave_url: "http://wave.webaim.org/report?url=http://cat.lib.unimelb.edu.au/"},
  {report_id: 2, page_url: "http://coursesearch.unimelb.edu.au/", page_title: "Study in Melbourne, Australia \u2014 Courses at The University of Melbourne, Australia", wave_url: "http://wave.webaim.org/report?url=http://coursesearch.unimelb.edu.au/"},
  {report_id: 2, page_url: "http://courseworks.unimelb.edu.au/", page_title: "Home : CourseWorks", wave_url: "http://wave.webaim.org/report?url=http://courseworks.unimelb.edu.au/"}
])
Category.create!([
  {page_id: 1, category_name: "error", description_name: "Missing form label", description_title: "label_missing", count: 1},
  {page_id: 1, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 4},
  {page_id: 1, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 1, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 1, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 8},
  {page_id: 1, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 20},
  {page_id: 1, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 1, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 2},
  {page_id: 2, category_name: "error", description_name: "Empty heading", description_title: "heading_empty", count: 1},
  {page_id: 2, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 2, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 2, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 16},
  {page_id: 2, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 11},
  {page_id: 2, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 2, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 2, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 2},
  {page_id: 3, category_name: "error", description_name: "Missing alternative text", description_title: "alt_missing", count: 2},
  {page_id: 3, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 3, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 3},
  {page_id: 3, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 3, category_name: "alert", description_name: "Broken same-page link", description_title: "link_internal_broken", count: 1},
  {page_id: 3, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 7},
  {page_id: 3, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 3},
  {page_id: 3, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 3, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 4, category_name: "error", description_name: "Empty heading", description_title: "heading_empty", count: 2},
  {page_id: 4, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 4, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 4, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 4, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 7},
  {page_id: 4, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 2},
  {page_id: 4, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 4, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 5, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 5, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 5, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 11},
  {page_id: 5, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 7},
  {page_id: 5, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 5, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 5, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 2},
  {page_id: 6, category_name: "error", description_name: "Empty heading", description_title: "heading_empty", count: 1},
  {page_id: 6, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 1},
  {page_id: 6, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 6, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 6, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 10},
  {page_id: 6, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 8},
  {page_id: 6, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 6, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 6, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 3},
  {page_id: 7, category_name: "error", description_name: "Missing form label", description_title: "label_missing", count: 2},
  {page_id: 7, category_name: "alert", description_name: "Suspicious alternative text", description_title: "alt_suspicious", count: 1},
  {page_id: 7, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 7, category_name: "alert", description_name: "Orphaned form label", description_title: "label_orphaned", count: 2},
  {page_id: 7, category_name: "alert", description_name: "Fieldset missing legend", description_title: "legend_missing", count: 1},
  {page_id: 7, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 7, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 7},
  {page_id: 7, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 2},
  {page_id: 7, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 7, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 8, category_name: "alert", description_name: "Redundant alternative text", description_title: "alt_redundant", count: 3},
  {page_id: 8, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 8, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 8, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 8, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 13},
  {page_id: 8, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 8},
  {page_id: 8, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 8, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 8, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 3},
  {page_id: 9, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 9, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 9, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 13},
  {page_id: 9, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 8},
  {page_id: 9, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 9, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 9, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 4},
  {page_id: 10, category_name: "alert", description_name: "Suspicious alternative text", description_title: "alt_suspicious", count: 1},
  {page_id: 10, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 10, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 10, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 7},
  {page_id: 10, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 2},
  {page_id: 10, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 3},
  {page_id: 10, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 11, category_name: "alert", description_name: "Suspicious alternative text", description_title: "alt_suspicious", count: 4},
  {page_id: 11, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 11, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 11, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 11, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 8},
  {page_id: 11, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 11, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 12, category_name: "error", description_name: "Missing alternative text", description_title: "alt_missing", count: 1},
  {page_id: 12, category_name: "error", description_name: "Linked image missing alternative text", description_title: "alt_link_missing", count: 6},
  {page_id: 12, category_name: "error", description_name: "Document language missing", description_title: "language_missing", count: 1},
  {page_id: 12, category_name: "error", description_name: "Empty button", description_title: "button_empty", count: 3},
  {page_id: 12, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 5},
  {page_id: 12, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 12, category_name: "alert", description_name: "Unlabeled form element with title", description_title: "label_title", count: 1},
  {page_id: 12, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 12, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 6},
  {page_id: 12, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 12, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 13, category_name: "error", description_name: "Missing form label", description_title: "label_missing", count: 1},
  {page_id: 13, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 13, category_name: "alert", description_name: "Orphaned form label", description_title: "label_orphaned", count: 1},
  {page_id: 13, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 13, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 1},
  {page_id: 13, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 1},
  {page_id: 13, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 13, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 14, category_name: "error", description_name: "Missing form label", description_title: "label_missing", count: 1},
  {page_id: 14, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 14, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 10},
  {page_id: 15, category_name: "error", description_name: "Missing form label", description_title: "label_missing", count: 1},
  {page_id: 15, category_name: "error", description_name: "Broken skip link", description_title: "link_skip_broken", count: 2},
  {page_id: 15, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 15, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 6},
  {page_id: 15, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 10},
  {page_id: 15, category_name: "alert", description_name: "JavaScript jump menu", description_title: "javascript_jumpmenu", count: 1},
  {page_id: 15, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 15, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 10},
  {page_id: 16, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 3},
  {page_id: 16, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 5},
  {page_id: 16, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 1},
  {page_id: 16, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 9},
  {page_id: 16, category_name: "alert", description_name: "Tabindex", description_title: "tabindex", count: 1},
  {page_id: 16, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 356},
  {page_id: 17, category_name: "error", description_name: "Linked image missing alternative text", description_title: "alt_link_missing", count: 6},
  {page_id: 17, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 1},
  {page_id: 17, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 17, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 5},
  {page_id: 17, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 12},
  {page_id: 17, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 17, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 4},
  {page_id: 18, category_name: "error", description_name: "Document language missing", description_title: "language_missing", count: 1},
  {page_id: 18, category_name: "error", description_name: "Page refreshes or redirects", description_title: "meta_refresh", count: 1},
  {page_id: 18, category_name: "alert", description_name: "Unlabeled form element with title", description_title: "label_title", count: 1},
  {page_id: 18, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 18, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 4},
  {page_id: 19, category_name: "error", description_name: "Broken skip link", description_title: "link_skip_broken", count: 1},
  {page_id: 19, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 19, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 19, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 20, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 20, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 3},
  {page_id: 20, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 12},
  {page_id: 20, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 6},
  {page_id: 20, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 20, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1}
])
