Category.create!([
  {page_id: 84, category_name: "error", description_name: "Missing alternative text", description_title: "alt_missing", count: 1},
  {page_id: 84, category_name: "error", description_name: "Linked image missing alternative text", description_title: "alt_link_missing", count: 6},
  {page_id: 84, category_name: "error", description_name: "Document language missing", description_title: "language_missing", count: 1},
  {page_id: 84, category_name: "error", description_name: "Empty button", description_title: "button_empty", count: 3},
  {page_id: 84, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 5},
  {page_id: 84, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 84, category_name: "alert", description_name: "Unlabeled form element with title", description_title: "label_title", count: 1},
  {page_id: 84, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 84, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 6},
  {page_id: 84, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 84, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 85, category_name: "error", description_name: "Missing form label", description_title: "label_missing", count: 1},
  {page_id: 85, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 85, category_name: "alert", description_name: "Orphaned form label", description_title: "label_orphaned", count: 1},
  {page_id: 85, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 85, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 1},
  {page_id: 85, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 1},
  {page_id: 85, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 85, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 86, category_name: "error", description_name: "Missing form label", description_title: "label_missing", count: 1},
  {page_id: 86, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 86, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 10},
  {page_id: 87, category_name: "error", description_name: "Missing form label", description_title: "label_missing", count: 1},
  {page_id: 87, category_name: "error", description_name: "Broken skip link", description_title: "link_skip_broken", count: 2},
  {page_id: 87, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 87, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 6},
  {page_id: 87, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 10},
  {page_id: 87, category_name: "alert", description_name: "JavaScript jump menu", description_title: "javascript_jumpmenu", count: 1},
  {page_id: 87, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 87, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 20},
  {page_id: 88, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 5},
  {page_id: 88, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 1},
  {page_id: 88, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 9},
  {page_id: 88, category_name: "alert", description_name: "Tabindex", description_title: "tabindex", count: 1},
  {page_id: 88, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 356},
  {page_id: 89, category_name: "error", description_name: "Linked image missing alternative text", description_title: "alt_link_missing", count: 6},
  {page_id: 89, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 1},
  {page_id: 89, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 89, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 5},
  {page_id: 89, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 12},
  {page_id: 89, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 89, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 4},
  {page_id: 90, category_name: "error", description_name: "Document language missing", description_title: "language_missing", count: 1},
  {page_id: 90, category_name: "error", description_name: "Page refreshes or redirects", description_title: "meta_refresh", count: 1},
  {page_id: 90, category_name: "alert", description_name: "Unlabeled form element with title", description_title: "label_title", count: 1},
  {page_id: 90, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 90, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 4},
  {page_id: 91, category_name: "error", description_name: "Broken skip link", description_title: "link_skip_broken", count: 1},
  {page_id: 91, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 91, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 91, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 92, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 92, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 3},
  {page_id: 92, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 12},
  {page_id: 92, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 6},
  {page_id: 92, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 144, category_name: "error", description_name: "Missing alternative text", description_title: "alt_missing", count: 4},
  {page_id: 144, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 144, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 2},
  {page_id: 144, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 5},
  {page_id: 144, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 11},
  {page_id: 144, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 145, category_name: "error", description_name: "Missing alternative text", description_title: "alt_missing", count: 4},
  {page_id: 145, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 145, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 2},
  {page_id: 145, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 3},
  {page_id: 145, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 4},
  {page_id: 145, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 146, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 7},
  {page_id: 146, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 146, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 2},
  {page_id: 146, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 1},
  {page_id: 146, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 147, category_name: "alert", description_name: "Redundant alternative text", description_title: "alt_redundant", count: 2},
  {page_id: 137, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 137, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 137, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 11},
  {page_id: 137, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 7},
  {page_id: 137, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 137, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 137, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 2},
  {page_id: 138, category_name: "error", description_name: "Empty heading", description_title: "heading_empty", count: 1},
  {page_id: 138, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 1},
  {page_id: 138, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 138, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 138, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 10},
  {page_id: 138, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 8},
  {page_id: 138, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 138, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 138, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 3},
  {page_id: 139, category_name: "error", description_name: "Missing form label", description_title: "label_missing", count: 2},
  {page_id: 139, category_name: "alert", description_name: "Suspicious alternative text", description_title: "alt_suspicious", count: 1},
  {page_id: 139, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 139, category_name: "alert", description_name: "Orphaned form label", description_title: "label_orphaned", count: 2},
  {page_id: 139, category_name: "alert", description_name: "Fieldset missing legend", description_title: "legend_missing", count: 1},
  {page_id: 139, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 139, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 7},
  {page_id: 139, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 2},
  {page_id: 139, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 139, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 140, category_name: "alert", description_name: "Redundant alternative text", description_title: "alt_redundant", count: 3},
  {page_id: 140, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 140, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 140, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 140, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 13},
  {page_id: 140, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 8},
  {page_id: 140, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 140, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 140, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 3},
  {page_id: 141, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 141, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 141, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 13},
  {page_id: 141, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 8},
  {page_id: 141, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 141, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 141, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 4},
  {page_id: 142, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 2},
  {page_id: 142, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 142, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 142, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 7},
  {page_id: 142, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 2},
  {page_id: 142, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 142, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 143, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 143, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 143, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 7},
  {page_id: 143, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 2},
  {page_id: 143, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 143, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 147, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 5},
  {page_id: 147, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 2},
  {page_id: 147, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 9},
  {page_id: 147, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 1},
  {page_id: 147, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 92, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 93, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 3},
  {page_id: 93, category_name: "alert", description_name: "Suspicious alternative text", description_title: "alt_suspicious", count: 3},
  {page_id: 93, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 2},
  {page_id: 93, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 2},
  {page_id: 93, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 1},
  {page_id: 93, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 94, category_name: "error", description_name: "Linked image missing alternative text", description_title: "alt_link_missing", count: 3},
  {page_id: 94, category_name: "error", description_name: "Missing form label", description_title: "label_missing", count: 1},
  {page_id: 94, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 2},
  {page_id: 94, category_name: "alert", description_name: "Suspicious alternative text", description_title: "alt_suspicious", count: 4},
  {page_id: 94, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 4},
  {page_id: 94, category_name: "alert", description_name: "Missing first level heading", description_title: "h1_missing", count: 1},
  {page_id: 94, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 1},
  {page_id: 94, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 5},
  {page_id: 94, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 95, category_name: "error", description_name: "Missing alternative text", description_title: "alt_missing", count: 1},
  {page_id: 95, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 5},
  {page_id: 95, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 95, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 10},
  {page_id: 95, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 95, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 95, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 96, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 96, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 2},
  {page_id: 96, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 4},
  {page_id: 96, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 96, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 97, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 97, category_name: "alert", description_name: "Orphaned form label", description_title: "label_orphaned", count: 2},
  {page_id: 97, category_name: "alert", description_name: "Fieldset missing legend", description_title: "legend_missing", count: 1},
  {page_id: 97, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 97, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 1},
  {page_id: 97, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 97, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 98, category_name: "error", description_name: "Linked image missing alternative text", description_title: "alt_link_missing", count: 7},
  {page_id: 98, category_name: "error", description_name: "Empty button", description_title: "button_empty", count: 4},
  {page_id: 98, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 13},
  {page_id: 98, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 98, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 98, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 5},
  {page_id: 98, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 11},
  {page_id: 98, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 98, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 98, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 1},
  {page_id: 99, category_name: "error", description_name: "Missing alternative text", description_title: "alt_missing", count: 10},
  {page_id: 99, category_name: "error", description_name: "Linked image missing alternative text", description_title: "alt_link_missing", count: 5},
  {page_id: 99, category_name: "error", description_name: "Missing form label", description_title: "label_missing", count: 2},
  {page_id: 99, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 8},
  {page_id: 99, category_name: "alert", description_name: "Redundant alternative text", description_title: "alt_redundant", count: 2},
  {page_id: 99, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 99, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 2},
  {page_id: 99, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 99, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 6},
  {page_id: 99, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 2},
  {page_id: 99, category_name: "alert", description_name: "JavaScript jump menu", description_title: "javascript_jumpmenu", count: 1},
  {page_id: 99, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 99, category_name: "alert", description_name: "Very small text", description_title: "text_small", count: 5},
  {page_id: 100, category_name: "alert", description_name: "Fieldset missing legend", description_title: "legend_missing", count: 2},
  {page_id: 100, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 100, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 100, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 7},
  {page_id: 100, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 101, category_name: "alert", description_name: "Fieldset missing legend", description_title: "legend_missing", count: 2},
  {page_id: 101, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 101, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 101, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 3},
  {page_id: 101, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 102, category_name: "error", description_name: "Linked image missing alternative text", description_title: "alt_link_missing", count: 6},
  {page_id: 102, category_name: "error", description_name: "Document language missing", description_title: "language_missing", count: 1},
  {page_id: 102, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 102, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 102, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 6},
  {page_id: 102, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 11},
  {page_id: 102, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 103, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 103, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 103, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 2},
  {page_id: 103, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 103, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 103, category_name: "alert", description_name: "Very small text", description_title: "text_small", count: 1},
  {page_id: 104, category_name: "error", description_name: "Document language missing", description_title: "language_missing", count: 1},
  {page_id: 104, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 105, category_name: "error", description_name: "Missing form label", description_title: "label_missing", count: 3},
  {page_id: 105, category_name: "error", description_name: "Document language missing", description_title: "language_missing", count: 1},
  {page_id: 105, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 105, category_name: "alert", description_name: "Fieldset missing legend", description_title: "legend_missing", count: 2},
  {page_id: 105, category_name: "alert", description_name: "Missing first level heading", description_title: "h1_missing", count: 1},
  {page_id: 105, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 1},
  {page_id: 106, category_name: "error", description_name: "Multiple form labels", description_title: "label_multiple", count: 2},
  {page_id: 106, category_name: "error", description_name: "Broken skip link", description_title: "link_skip_broken", count: 2},
  {page_id: 106, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 106, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 106, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 1},
  {page_id: 106, category_name: "alert", description_name: "Link to Word document", description_title: "link_word", count: 2},
  {page_id: 106, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 5},
  {page_id: 106, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 106, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 1},
  {page_id: 107, category_name: "error", description_name: "Empty button", description_title: "button_empty", count: 3},
  {page_id: 107, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 1},
  {page_id: 107, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 107, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 2},
  {page_id: 107, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 6},
  {page_id: 107, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 10},
  {page_id: 107, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 12},
  {page_id: 107, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 4},
  {page_id: 108, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 1},
  {page_id: 108, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 108, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 2},
  {page_id: 108, category_name: "alert", description_name: "Broken same-page link", description_title: "link_internal_broken", count: 1},
  {page_id: 108, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 4},
  {page_id: 108, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 13},
  {page_id: 108, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 109, category_name: "error", description_name: "Missing alternative text", description_title: "alt_missing", count: 1},
  {page_id: 109, category_name: "error", description_name: "Image button missing alternative text", description_title: "alt_input_missing", count: 1},
  {page_id: 109, category_name: "alert", description_name: "Redundant alternative text", description_title: "alt_redundant", count: 3},
  {page_id: 109, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 109, category_name: "alert", description_name: "Unlabeled form element with title", description_title: "label_title", count: 1},
  {page_id: 109, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 109, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 2},
  {page_id: 109, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 6},
  {page_id: 109, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 109, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 6},
  {page_id: 110, category_name: "error", description_name: "Broken skip link", description_title: "link_skip_broken", count: 4},
  {page_id: 110, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 110, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 110, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 110, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 110, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 3},
  {page_id: 111, category_name: "error", description_name: "Missing form label", description_title: "label_missing", count: 1},
  {page_id: 111, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 2},
  {page_id: 111, category_name: "alert", description_name: "Redundant alternative text", description_title: "alt_redundant", count: 3},
  {page_id: 111, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 111, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 111, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 4},
  {page_id: 111, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 1},
  {page_id: 111, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 12},
  {page_id: 111, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 111, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 111, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 10},
  {page_id: 112, category_name: "error", description_name: "Broken skip link", description_title: "link_skip_broken", count: 2},
  {page_id: 112, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 1},
  {page_id: 112, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 19},
  {page_id: 113, category_name: "alert", description_name: "Redundant alternative text", description_title: "alt_redundant", count: 3},
  {page_id: 113, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 113, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 113, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 113, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 15},
  {page_id: 113, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 113, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 3},
  {page_id: 114, category_name: "alert", description_name: "Fieldset missing legend", description_title: "legend_missing", count: 2},
  {page_id: 114, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 114, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 1},
  {page_id: 114, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 7},
  {page_id: 114, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 115, category_name: "error", description_name: "Linked image missing alternative text", description_title: "alt_link_missing", count: 32},
  {page_id: 115, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 5},
  {page_id: 115, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 115, category_name: "alert", description_name: "Orphaned form label", description_title: "label_orphaned", count: 1},
  {page_id: 115, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 115, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 115, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 8},
  {page_id: 115, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 94},
  {page_id: 115, category_name: "alert", description_name: "Flash", description_title: "flash", count: 1},
  {page_id: 115, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 115, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 115, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 22},
  {page_id: 116, category_name: "error", description_name: "Linked image missing alternative text", description_title: "alt_link_missing", count: 1},
  {page_id: 116, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 116, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 6},
  {page_id: 116, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 15},
  {page_id: 116, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 117, category_name: "error", description_name: "Linked image missing alternative text", description_title: "alt_link_missing", count: 4},
  {page_id: 117, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 117, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 2},
  {page_id: 117, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 1},
  {page_id: 117, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 13},
  {page_id: 117, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 117, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 118, category_name: "error", description_name: "Missing alternative text", description_title: "alt_missing", count: 1},
  {page_id: 118, category_name: "error", description_name: "Image button missing alternative text", description_title: "alt_input_missing", count: 1},
  {page_id: 118, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 118, category_name: "alert", description_name: "Orphaned form label", description_title: "label_orphaned", count: 2},
  {page_id: 118, category_name: "alert", description_name: "Fieldset missing legend", description_title: "legend_missing", count: 1},
  {page_id: 118, category_name: "alert", description_name: "Unlabeled form element with title", description_title: "label_title", count: 1},
  {page_id: 118, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 118, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 118, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 118, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 119, category_name: "error", description_name: "Missing alternative text", description_title: "alt_missing", count: 3},
  {page_id: 119, category_name: "error", description_name: "Linked image missing alternative text", description_title: "alt_link_missing", count: 4},
  {page_id: 119, category_name: "error", description_name: "Empty heading", description_title: "heading_empty", count: 1},
  {page_id: 119, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 1},
  {page_id: 119, category_name: "alert", description_name: "Unlabeled form element with title", description_title: "label_title", count: 2},
  {page_id: 119, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 119, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 6},
  {page_id: 119, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 130},
  {page_id: 119, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 119, category_name: "alert", description_name: "Device dependent event handler", description_title: "event_handler", count: 3},
  {page_id: 119, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 3},
  {page_id: 119, category_name: "alert", description_name: "Very small text", description_title: "text_small", count: 1},
  {page_id: 120, category_name: "error", description_name: "Linked image missing alternative text", description_title: "alt_link_missing", count: 32},
  {page_id: 120, category_name: "error", description_name: "Document language missing", description_title: "language_missing", count: 1},
  {page_id: 120, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 1},
  {page_id: 120, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 120, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 2},
  {page_id: 120, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 26},
  {page_id: 120, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 120, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 121, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 4},
  {page_id: 121, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 3},
  {page_id: 121, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 8},
  {page_id: 121, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 121, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 122, category_name: "error", description_name: "Missing alternative text", description_title: "alt_missing", count: 4},
  {page_id: 122, category_name: "error", description_name: "Missing form label", description_title: "label_missing", count: 1},
  {page_id: 122, category_name: "error", description_name: "Empty button", description_title: "button_empty", count: 1},
  {page_id: 122, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 2},
  {page_id: 122, category_name: "alert", description_name: "Fieldset missing legend", description_title: "legend_missing", count: 1},
  {page_id: 122, category_name: "alert", description_name: "Unlabeled form element with title", description_title: "label_title", count: 1},
  {page_id: 122, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 122, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 4},
  {page_id: 123, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 123, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 123, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 123, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 124, category_name: "error", description_name: "Linked image missing alternative text", description_title: "alt_link_missing", count: 2},
  {page_id: 124, category_name: "error", description_name: "Document language missing", description_title: "language_missing", count: 1},
  {page_id: 124, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 124, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 4},
  {page_id: 124, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 6},
  {page_id: 124, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 15},
  {page_id: 124, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 125, category_name: "error", description_name: "Broken skip link", description_title: "link_skip_broken", count: 1},
  {page_id: 125, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 125, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 125, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 2},
  {page_id: 125, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 1},
  {page_id: 125, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 2},
  {page_id: 125, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 2},
  {page_id: 125, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 125, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 4},
  {page_id: 126, category_name: "error", description_name: "Broken skip link", description_title: "link_skip_broken", count: 4},
  {page_id: 126, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 2},
  {page_id: 126, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 2},
  {page_id: 126, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 2},
  {page_id: 126, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 1},
  {page_id: 126, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 126, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 4},
  {page_id: 126, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 1},
  {page_id: 127, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 2},
  {page_id: 127, category_name: "error", description_name: "Broken skip link", description_title: "link_skip_broken", count: 4},
  {page_id: 127, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 127, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 2},
  {page_id: 127, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 2},
  {page_id: 127, category_name: "alert", description_name: "Suspicious link text", description_title: "link_suspicious", count: 1},
  {page_id: 127, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 3},
  {page_id: 127, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 1},
  {page_id: 127, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 127, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 4},
  {page_id: 127, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 1},
  {page_id: 128, category_name: "error", description_name: "Empty link", description_title: "link_empty", count: 2},
  {page_id: 128, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 128, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 2},
  {page_id: 128, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 2},
  {page_id: 128, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 3},
  {page_id: 128, category_name: "alert", description_name: "Link to PDF document", description_title: "link_pdf", count: 1},
  {page_id: 128, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 128, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 3},
  {page_id: 128, category_name: "alert", description_name: "Redundant title text", description_title: "title_redundant", count: 1},
  {page_id: 129, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 129, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 3},
  {page_id: 129, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 1},
  {page_id: 129, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 4},
  {page_id: 130, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 130, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 130, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 130, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 1},
  {page_id: 130, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 130, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 131, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 131, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 2},
  {page_id: 131, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 131, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1},
  {page_id: 132, category_name: "alert", description_name: "A nearby image has the same alternative text", description_title: "alt_duplicate", count: 1},
  {page_id: 132, category_name: "alert", description_name: "Skipped heading level", description_title: "heading_skipped", count: 1},
  {page_id: 132, category_name: "alert", description_name: "Possible heading", description_title: "heading_possible", count: 1},
  {page_id: 132, category_name: "alert", description_name: "Broken same-page link", description_title: "link_internal_broken", count: 10},
  {page_id: 132, category_name: "alert", description_name: "Redundant link", description_title: "link_redundant", count: 1},
  {page_id: 132, category_name: "alert", description_name: "Noscript element", description_title: "noscript", count: 1},
  {page_id: 132, category_name: "alert", description_name: "Accesskey", description_title: "accesskey", count: 1}
])
Page.create!([
  {report_id: 19, page_url: "http://www.cis.unimelb.edu.au/", page_title: "Computing and Information Systems, University of Melbourne", wave_url: "http://wave.webaim.org/report?url=http://www.cis.unimelb.edu.au/"},
  {report_id: 19, page_url: "http://www.cis.unimelb.edu.au/study/", page_title: "Study With Us: Computing and Information Systems, University of Melbourne", wave_url: "http://wave.webaim.org/report?url=http://www.cis.unimelb.edu.au/study/"},
  {report_id: 19, page_url: "http://www.eng.unimelb.edu.au/about/advisory-groups/", page_title: "Industry Advisory Groups: Melbourne School of Engineering, University of Melbourne", wave_url: "http://wave.webaim.org/report?url=http://www.eng.unimelb.edu.au/about/advisory-groups/"},
  {report_id: 19, page_url: "http://www.eng.unimelb.edu.au/study/graduate/master-eng-software-business.html", page_title: "Master of Engineering (Software with Business): Melbourne School of Engineering, University of Melbourne", wave_url: "http://wave.webaim.org/report?url=http://www.eng.unimelb.edu.au/study/graduate/master-eng-software-business.html"},
  {report_id: 18, page_url: "http://gradresearch.unimelb.edu.au/news/index.html", page_title: "The Melbourne School Of Graduate Research - News", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/news/index.html"},
  {report_id: 18, page_url: "http://gradresearch.unimelb.edu.au/handbooks/index.html", page_title: "The Melbourne School Of Graduate Research - Handbooks", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/handbooks/index.html"},
  {report_id: 18, page_url: "http://gradresearch.unimelb.edu.au/messenger/index.html", page_title: "The Melbourne School Of Graduate Research - Messenger", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/messenger/index.html"},
  {report_id: 18, page_url: "http://gradresearch.unimelb.edu.au/programs/index.html", page_title: "The Melbourne School Of Graduate Research - Research Training & Professional Development", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/programs/index.html"},
  {report_id: 18, page_url: "http://gradresearch.unimelb.edu.au/msgr/", page_title: "The Melbourne School Of Graduate Research - About the Melbourne School of Graduate Research", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/msgr/"},
  {report_id: 18, page_url: "http://gradresearch.unimelb.edu.au/thesis/gallery.html", page_title: "The Melbourne School Of Graduate Research - Orientation & Induction", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/thesis/gallery.html"},
  {report_id: 18, page_url: "http://gradresearch.unimelb.edu.au/news/opportunities.html", page_title: "The Melbourne School Of Graduate Research - News", wave_url: "http://wave.webaim.org/report?url=http://gradresearch.unimelb.edu.au/news/opportunities.html"},
  {report_id: 16, page_url: "http://arts.unimelb.edu.au/", page_title: "Faculty of Arts | Faculty of Arts", wave_url: "http://wave.webaim.org/report?url=http://arts.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://ask.unimelb.edu.au/", page_title: "ask.unimelb : Ask Unimelb", wave_url: "http://wave.webaim.org/report?url=http://ask.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://blog.le.unimelb.edu.au/", page_title: "Learning Environments blog", wave_url: "http://wave.webaim.org/report?url=http://blog.le.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://blogs.unimelb.edu.au/ask-counselling/", page_title: "Ask Counselling | Counselling and Psychological Services", wave_url: "http://wave.webaim.org/report?url=http://blogs.unimelb.edu.au/ask-counselling/"},
  {report_id: 16, page_url: "http://blogs.unimelb.edu.au/staffnews/", page_title: "Staff News \u00BB Just another blogs.unimelb weblog", wave_url: "http://wave.webaim.org/report?url=http://blogs.unimelb.edu.au/staffnews/"},
  {report_id: 16, page_url: "http://careers.unimelb.edu.au/home", page_title: "Home : Careers and Employment", wave_url: "http://wave.webaim.org/report?url=http://careers.unimelb.edu.au/home"},
  {report_id: 16, page_url: "http://cat.lib.unimelb.edu.au/", page_title: "Catalogue : Library : The University of Melbourne", wave_url: "http://wave.webaim.org/report?url=http://cat.lib.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://coursesearch.unimelb.edu.au/", page_title: "Study in Melbourne, Australia \u2014 Courses at The University of Melbourne, Australia", wave_url: "http://wave.webaim.org/report?url=http://coursesearch.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://courseworks.unimelb.edu.au/", page_title: "Home : CourseWorks", wave_url: "http://wave.webaim.org/report?url=http://courseworks.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://digitisation.unimelb.edu.au/", page_title: "Home : University Digitisation Centre", wave_url: "http://wave.webaim.org/report?url=http://digitisation.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://education.unimelb.edu.au/", page_title: "Home : MGSE", wave_url: "http://wave.webaim.org/report?url=http://education.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://elc.unimelb.edu.au/index.html", page_title: "Early Learning Centre : : The University of Melbourne", wave_url: "http://wave.webaim.org/report?url=http://elc.unimelb.edu.au/index.html"},
  {report_id: 16, page_url: "http://enrolment.unimelb.edu.au/", page_title: "Home : Enrolment", wave_url: "http://wave.webaim.org/report?url=http://enrolment.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://equity.unimelb.edu.au/", page_title: "Equity and Student Engagement : Melbourne Students & Learning", wave_url: "http://wave.webaim.org/report?url=http://equity.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://fbe.unimelb.edu.au/", page_title: "Home | Faculty of Business and Economics", wave_url: "http://wave.webaim.org/report?url=http://fbe.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://futurestudents.unimelb.edu.au/", page_title: "Home: Future Students : Future Students", wave_url: "http://wave.webaim.org/report?url=http://futurestudents.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://government.unimelb.edu.au/", page_title: "Home Melbourne School of Government", wave_url: "http://wave.webaim.org/report?url=http://government.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://graduate.arts.unimelb.edu.au/", page_title: "Home Graduate School of Humanities and Social Sciences", wave_url: "http://wave.webaim.org/report?url=http://graduate.arts.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://graduate.science.unimelb.edu.au/", page_title: "Home | Melbourne Graduate School of Science", wave_url: "http://wave.webaim.org/report?url=http://graduate.science.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://graduation.unimelb.edu.au/", page_title: "Home - Graduating at Melbourne", wave_url: "http://wave.webaim.org/report?url=http://graduation.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://healthy.unimelb.edu.au/", page_title: "Information module", wave_url: "http://wave.webaim.org/report?url=http://healthy.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://host.engagementprograms.com/Student/Logon", page_title: "University of Melbourne Student Union - Student Logon", wave_url: "http://wave.webaim.org/report?url=http://host.engagementprograms.com/Student/Logon"},
  {report_id: 16, page_url: "http://hr.unimelb.edu.au/", page_title: "Home - Human Resources - The University of Melbourne", wave_url: "http://wave.webaim.org/report?url=http://hr.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://iehu.unimelb.edu.au/", page_title: "Home : Indigenous Eye Health Unit", wave_url: "http://wave.webaim.org/report?url=http://iehu.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://land-environment.unimelb.edu.au/", page_title: "Melbourne School of Land and Environment : The University of Melbourne", wave_url: "http://wave.webaim.org/report?url=http://land-environment.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://le.unimelb.edu.au/", page_title: "Learning Environments : The University of Melbourne", wave_url: "http://wave.webaim.org/report?url=http://le.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://learningandteaching.unimelb.edu.au/", page_title: "Home : Learning & Teaching", wave_url: "http://wave.webaim.org/report?url=http://learningandteaching.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://library.unimelb.edu.au/", page_title: "home : Library", wave_url: "http://wave.webaim.org/report?url=http://library.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://library.unimelb.edu.au/digitalcollections/home", page_title: "Home - Digital Collections", wave_url: "http://wave.webaim.org/report?url=http://library.unimelb.edu.au/digitalcollections/home"},
  {report_id: 16, page_url: "http://lms.unimelb.edu.au/", page_title: "Learning Management System : Learning Environments : The University of Melbourne", wave_url: "http://wave.webaim.org/report?url=http://lms.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://mbs.unimelb.edu.au/", page_title: "Home Melbourne Business School", wave_url: "http://wave.webaim.org/report?url=http://mbs.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://mdhs.unimelb.edu.au/", page_title: "Medicine, Dentistry and Health Sciences |", wave_url: "http://wave.webaim.org/report?url=http://mdhs.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://medicine.unimelb.edu.au/", page_title: "Home - Melbourne Medical School", wave_url: "http://wave.webaim.org/report?url=http://medicine.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://msi.unimelb.edu.au/", page_title: "Melbourne School of Information, University of Melbourne", wave_url: "http://wave.webaim.org/report?url=http://msi.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://msl.unimelb.edu.au/", page_title: "Home : Melbourne Students & Learning", wave_url: "http://wave.webaim.org/report?url=http://msl.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://musse.unimelb.edu.au/", page_title: "MUSSE | Melbourne University Staff / Student E-news", wave_url: "http://wave.webaim.org/report?url=http://musse.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://newsroom.melbourne.edu/", page_title: "The Melbourne Newsroom | newsroom.melbourne.edu", wave_url: "http://wave.webaim.org/report?url=http://newsroom.melbourne.edu/"},
  {report_id: 16, page_url: "http://nextsteps.unimelb.edu.au/", page_title: "Home - Next Steps", wave_url: "http://wave.webaim.org/report?url=http://nextsteps.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://pgh.unimelb.edu.au/", page_title: "Home \u2014 Melbourne School of Population and Global Health", wave_url: "http://wave.webaim.org/report?url=http://pgh.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://safercommunity.unimelb.edu.au/", page_title: "Home : Safer Community Program", wave_url: "http://wave.webaim.org/report?url=http://safercommunity.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://science.unimelb.edu.au/", page_title: "Home | Faculty of Science", wave_url: "http://wave.webaim.org/report?url=http://science.unimelb.edu.au/"},
  {report_id: 16, page_url: "http://services.unimelb.edu.au/academicskills/home", page_title: "Home : Academic Skills", wave_url: "http://wave.webaim.org/report?url=http://services.unimelb.edu.au/academicskills/home"},
  {report_id: 16, page_url: "http://services.unimelb.edu.au/chaplains", page_title: "Home : Chaplaincy", wave_url: "http://wave.webaim.org/report?url=http://services.unimelb.edu.au/chaplains"},
  {report_id: 16, page_url: "http://services.unimelb.edu.au/childcare/home", page_title: "Home : Childcare", wave_url: "http://wave.webaim.org/report?url=http://services.unimelb.edu.au/childcare/home"},
  {report_id: 16, page_url: "http://services.unimelb.edu.au/counsel/home", page_title: "Home : Counselling and Psychological Services", wave_url: "http://wave.webaim.org/report?url=http://services.unimelb.edu.au/counsel/home"},
  {report_id: 16, page_url: "http://services.unimelb.edu.au/disability/home", page_title: "Home : Disability Liaison", wave_url: "http://wave.webaim.org/report?url=http://services.unimelb.edu.au/disability/home"},
  {report_id: 16, page_url: "http://services.unimelb.edu.au/externalexam", page_title: "Home : External Exams", wave_url: "http://wave.webaim.org/report?url=http://services.unimelb.edu.au/externalexam"},
  {report_id: 16, page_url: "http://services.unimelb.edu.au/finaid", page_title: "Home : Financial Aid", wave_url: "http://wave.webaim.org/report?url=http://services.unimelb.edu.au/finaid"},
  {report_id: 16, page_url: "http://services.unimelb.edu.au/finder/home", page_title: "Services Finder", wave_url: "http://wave.webaim.org/report?url=http://services.unimelb.edu.au/finder/home"}
])
Report.create!([
  {report_date: "2014-12-12 00:00:00", submit_id: 2, pages_total: 5, pages_error: 2, total_errors: 4, total_alerts: 132, error_avg: "0.8"},
  {report_date: "2014-12-17 00:00:00", submit_id: 6, pages_total: 4, pages_error: 2, total_errors: 8, total_alerts: 63, error_avg: "2.0"},
  {report_date: "2014-12-17 00:00:00", submit_id: 2, pages_total: 7, pages_error: 2, total_errors: 4, total_alerts: 162, error_avg: "0.57"},
  {report_date: "2014-12-15 00:00:00", submit_id: 2, pages_total: 5, pages_error: 2, total_errors: 4, total_alerts: 132, error_avg: "0.8"},
  {report_date: "2014-12-18 00:00:00", submit_id: 6, pages_total: 4, pages_error: 2, total_errors: 8, total_alerts: 63, error_avg: "2.0"},
  {report_date: "2014-12-16 00:00:00", submit_id: 2, pages_total: 7, pages_error: 2, total_errors: 4, total_alerts: 162, error_avg: "0.5714285714285714"},
  {report_date: "2014-12-12 00:00:00", submit_id: 1, pages_total: 49, pages_error: 36, total_errors: 237, total_alerts: 1348, error_avg: "4.836734693877551"},
  {report_date: "2014-12-16 00:00:00", submit_id: 1, pages_total: 49, pages_error: 34, total_errors: 233, total_alerts: 1350, error_avg: "4.755102040816326"}
])
Submit.create!([
  {website_url: "http://gradresearch.unimelb.edu.au/", report_name: "Grad_research", pg_urls: "http://gradresearch.unimelb.edu.au/news/index.html,http://gradresearch.unimelb.edu.au/handbooks/index.html,http://gradresearch.unimelb.edu.au/messenger/index.html,http://gradresearch.unimelb.edu.au/programs/index.html,http://gradresearch.unimelb.edu.au/msgr/,http://gradresearch.unimelb.edu.au/thesis/gallery.html,http://gradresearch.unimelb.edu.au/news/opportunities.html", email_id: "nikki.vinayan@unimelb.edu.au", submit_date: "2014-12-17 00:00:00", report_run_status: "complete"},
  {website_url: "http://www.unimelb.edu.au/", report_name: "Varied Sample ", pg_urls: "http://arts.unimelb.edu.au/,http://ask.unimelb.edu.au/,http://blog.le.unimelb.edu.au/,http://blogs.unimelb.edu.au/ask-counselling/,http://blogs.unimelb.edu.au/staffnews/,http://careers.unimelb.edu.au/home,http://cat.lib.unimelb.edu.au/,http://coursesearch.unimelb.edu.au/,http://courseworks.unimelb.edu.au/,http://digitisation.unimelb.edu.au/,http://education.unimelb.edu.au/,http://elc.unimelb.edu.au/index.html,http://enrolment.unimelb.edu.au/,http://equity.unimelb.edu.au/,http://fbe.unimelb.edu.au/,http://futurestudents.unimelb.edu.au/,http://government.unimelb.edu.au/,http://graduate.arts.unimelb.edu.au/,http://graduate.science.unimelb.edu.au/,http://graduation.unimelb.edu.au/,http://healthy.unimelb.edu.au/,http://host.engagementprograms.com/Student/Logon,http://hr.unimelb.edu.au/,http://iehu.unimelb.edu.au/,http://land-environment.unimelb.edu.au/,http://le.unimelb.edu.au/,http://learningandteaching.unimelb.edu.au/,http://library.unimelb.edu.au/,http://library.unimelb.edu.au/digitalcollections/home,http://lms.unimelb.edu.au/,http://mbs.unimelb.edu.au/,http://mdhs.unimelb.edu.au/,http://medicine.unimelb.edu.au/,http://medicine.unimelb.edu.au/,http://msi.unimelb.edu.au/,http://msl.unimelb.edu.au/,http://musse.unimelb.edu.au/,http://newsroom.melbourne.edu/,http://nextsteps.unimelb.edu.au/,http://pgh.unimelb.edu.au/,http://safercommunity.unimelb.edu.au/,http://science.unimelb.edu.au/,http://services.unimelb.edu.au/academicskills/home,http://services.unimelb.edu.au/chaplains,http://services.unimelb.edu.au/childcare/home,http://services.unimelb.edu.au/counsel/home,http://services.unimelb.edu.au/disability/home,http://services.unimelb.edu.au/externalexam,http://services.unimelb.edu.au/finaid,http://services.unimelb.edu.au/finder/home", email_id: "nikki.vinayan@unimelb.edu.au", submit_date: "2014-12-16 00:00:00", report_run_status: "complete"},
  {website_url: "http://www.cis.unimelb.edu.au/", report_name: "ICT Unimelb", pg_urls: "http://www.cis.unimelb.edu.au/,http://www.cis.unimelb.edu.au/study/,http://www.eng.unimelb.edu.au/about/advisory-groups/,http://www.eng.unimelb.edu.au/study/graduate/master-eng-software-business.html", email_id: "nikki.vinayan@unimelb.edu.au", submit_date: "2014-12-18 00:00:00", report_run_status: "complete"}
])
